pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK11"
        
    }

    environment {
        ecs_cluster = "vproprod" #ecs cluster name
        ecs_service = "vpro-app-prod-svc" #ecs service name

    }
    
    stages {
      
        stage("deploy to Ecsprod") {
            steps {
                withAWS( credentials: 'Aws-creds', region: 'us-east-1' ) {
                   sh 'aws ecs update-service --cluster ${ecs_cluster} --service ${ecs_service} --force-new-deployment' 
            }
        }
    }
}   
    post {
    always {
        script {
            // Define variables
            def jobName = env.JOB_NAME
            def buildNumber = env.BUILD_NUMBER
            def build_timestamp = env.BUILD_TIMESTAMP
            def pipelineStatus = currentBuild.result ?: 'UNKNOWN'
            def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'

            // Create HTML email body
            def body = """
                <html>
                    <body>
                        <div style="border: 4px solid ${bannerColor}; padding: 10px;">
                            <h2>${jobName} - Build ${buildNumber}- ${build_timestamp}</h2>
                            <div style="background-color: ${bannerColor}; padding: 10px;">
                                <h3 style="color: white;">Pipeline Status: ${pipelineStatus.toUpperCase()}</h3>
                            </div>
                            <p>Check the <a href="${BUILD_URL}">console output</a>.</p>
                        </div>
                    </body>
                </html>
            """

            // Send email with the generated body
            emailext(
                subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
                body: body,
                to: 'boluwatifeadenle26@gmail.com',
                from: 'jenkins@example.com',
                replyTo: 'jenkins@example.com',
                mimeType: 'text/html'
                // attachmentsPattern: 'trivy-image-report.html'
            )
        }
    }
    }

}

